# Generated by Django 4.1 on 2022-10-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyectoFinal', '0003_remove_blog_imagen_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.DeleteModel(
            name='Img',
        ),
    ]
