# Generated by Django 4.1 on 2022-10-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyectoFinal', '0005_alter_blog_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'permissions': (('puede_publicar', 'Puede publicar'), ('puede_editar', 'Puede editar'), ('puede_eliminar', 'Puede eliminar'))},
        ),
        migrations.AlterField(
            model_name='blog',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes'),
        ),
    ]
