# Generated by Django 4.1 on 2022-10-25 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyectoFinal', '0006_alter_blog_options_alter_blog_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={},
        ),
    ]
